from attrs import define
from pyvider.cty.exceptions import CtyBoolValidationError as CtyBoolValidationError
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar

@define(frozen=True, slots=True)
class CtyBool(CtyType[bool]):
    ctype: ClassVar[str] = ...
    def validate(self, value: object) -> CtyValue[bool]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
    def is_primitive_type(self) -> bool: ...
