from attrs import define
from decimal import Decimal
from pyvider.cty.exceptions import CtyNumberValidationError as CtyNumberValidationError
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar

@define(frozen=True, slots=True)
class CtyNumber(CtyType[Decimal]):
    ctype: ClassVar[str] = ...
    def validate(self, value: object) -> CtyValue[Decimal]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
    def is_primitive_type(self) -> bool: ...
