import abc
from .types_base import CtyTypeProtocol as CtyTypeProtocol
from abc import ABC, abstractmethod
from attrs import define
from pyvider.cty.values import CtyValue as CtyValue
from typing import ClassVar, TypeVar

T = TypeVar('T')

@define(slots=True)
class CtyType[T](CtyTypeProtocol[T], ABC, metaclass=abc.ABCMeta):
    ctype: ClassVar[str | None] = ...
    @abstractmethod
    def validate(self, value: object) -> CtyValue[T]: ...
    @abstractmethod
    def equal(self, other: CtyType[T]) -> bool: ...
    @abstractmethod
    def usable_as(self, other: CtyType[T]) -> bool: ...
    def is_primitive_type(self) -> bool: ...
    def is_dynamic_type(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
