from _typeshed import Incomplete
from pyvider.cty.exceptions import CtyValidationError as CtyValidationError
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.types.structural import CtyDynamic as CtyDynamic
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any

class CtyCapsule(CtyType[Any]):
    name: Incomplete
    def __init__(self, capsule_name: str, py_type: type) -> None: ...
    @property
    def py_type(self) -> type: ...
    def validate(self, value: object) -> CtyValue[Any]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
    def __hash__(self) -> int: ...
