from pyvider.cty.values.base import CtyValue as CtyValue
from typing import Any, Protocol, TypeVar

T = TypeVar('T')

class CtyTypeProtocol(Protocol[T]):
    def validate(self, value: object) -> CtyValue[T]: ...
    def equal(self, other: Any) -> bool: ...
    def usable_as(self, other: Any) -> bool: ...
    def is_primitive_type(self) -> bool: ...
