from attrs import define, field
from pyvider.cty.exceptions import CtyMapValidationError as CtyMapValidationError, CtyTypeMismatchError as CtyTypeMismatchError, CtyValidationError as CtyValidationError, InvalidTypeError as InvalidTypeError
from pyvider.cty.path import CtyPath as CtyPath, KeyStep as KeyStep
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar, TypeVar

V = TypeVar('V')

@define(frozen=True, slots=True)
class CtyMap[V](CtyType[dict[str, V]]):
    ctype: ClassVar[str] = ...
    element_type: CtyType[V] = field(kw_only=True)
    def __attrs_post_init__(self) -> None: ...
    def validate(self, value: object) -> CtyValue[dict[str, V]]: ...
    def get(self, map_value: CtyValue[dict[str, V]], key: object, default: CtyValue[V] | None = None) -> CtyValue[V]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
