from attrs import define, field
from pyvider.cty.exceptions import CtySetValidationError as CtySetValidationError, CtyValidationError as CtyValidationError
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar, TypeVar

T = TypeVar('T')

@define(frozen=True, slots=True)
class CtySet[T](CtyType[frozenset[T]]):
    ctype: ClassVar[str] = ...
    element_type: CtyType[T] = field(kw_only=True)
    def __attrs_post_init__(self) -> None: ...
    def validate(self, value: object) -> CtyValue[frozenset[T]]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
