#
# SPDX-FileCopyrightText: Copyright (c) provide.io llc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

"""The collection half of the stdlib sweep table.

Collections, containers holding an unknown element, encoding and time, `format`,
bytes and conversion. Split out of `test_stdlib_sweep.py` at this repository's
500-line ceiling for a test file; the driver walks `CASES`, which is this list
concatenated onto `SCALAR_CASES`.
"""

from __future__ import annotations

from pyvider.cty import CtyBool, CtyList, CtyNumber, CtyString
from tests.compatibility._sweep_args import (
    UK,
    Arg,
    bl,
    by,
    lb,
    ln,
    ls,
    ls_uk,
    mn,
    mp,
    nm,
    nm_inf,
    nul,
    ob,
    sb,
    se,
    se_uk,
    sn,
    st,
)

COLLECTION_CASES: list[tuple[str, list[Arg]]] = [
    # collections
    ("distinct", [ls(["a", "a", "b"])]),
    ("compact", [ls(["a", "", "b"])]),
    ("concat", [ls(["a"]), ls(["b"])]),
    ("concat", [ls(["a"]), ln([1])]),
    ("concat", [ls(["a"]), lb([True])]),
    ("concat", [ln([1]), lb([True])]),
    ("concat", [ls(["a"]), nul(["list", "string"], CtyList(element_type=CtyString()))]),
    ("contains", [ls(["a"]), st("a")]),
    ("contains", [ls(["a"]), st("z")]),
    ("element", [ls(["a", "b"]), nm(1)]),
    ("element", [ls(["a", "b"]), nm(3)]),
    ("index", [ls(["a", "b"]), st("b")]),
    ("index", [ls(["a", "b"]), st("z")]),
    ("hasindex", [ls(["a"]), nm(0)]),
    ("hasindex", [ls(["a"]), nm(9)]),
    # A key `big.Float.Int64()` cannot read exactly names no position, so it is
    # a False rather than a truncation. `index` then refuses it.
    ("hasindex", [ls(["a", "b", "c"]), nm(1.5)]),
    ("hasindex", [ls(["a", "b", "c"]), nm(-1)]),
    ("hasindex", [ls(["a", "b", "c"]), nm(1e30)]),
    ("index", [ls(["a", "b", "c"]), nm(1.5)]),
    ("index", [ls(["a", "b", "c"]), nm(1)]),
    ("keys", [mp({"b": "1", "a": "2"})]),
    ("values", [mp({"b": "1", "a": "2"})]),
    ("values", [mp({})]),
    ("lookup", [mp({"a": "1"}), st("a"), st("z")]),
    ("lookup", [mp({"a": "1"}), st("q"), st("z")]),
    ("merge", [mp({"a": "1"}), mp({"b": "2"})]),
    ("merge", [mp({"a": "1"}), mp({"a": "2"})]),
    ("merge", [ob({"a": "1"}), ob({"b": "2"})]),
    ("merge", [mp({"a": "1"}), ob({"b": "2"})]),
    ("merge", [mp({"a": "1"}), mn({"b": 2})]),
    ("merge", [mp({})]),
    ("reverselist", [ls(["a", "b"])]),
    ("sort", [ls(["b", "a", "C"])]),
    ("slice", [ls(["a", "b", "c"]), nm(1), nm(3)]),
    ("zipmap", [ls(["a", "b"]), ls(["1", "2"])]),
    ("setunion", [se(["a"]), se(["b"])]),
    ("setunion", [se(["a"])]),
    ("setunion", [se([]), se([])]),
    ("setunion", [se(["a"]), se(["a"])]),
    ("setunion", [se(["a"]), sb([True])]),
    ("setunion", [se(["a"]), sn([1])]),
    ("setintersection", [se(["a", "b"]), se(["b"])]),
    ("setintersection", [se(["a"]), se(["b"])]),
    ("setsubtract", [se(["a", "b"]), se(["b"])]),
    ("setsubtract", [se(["a"]), se(["a"])]),
    ("setsymmetricdifference", [se(["a", "b"]), se(["b", "c"])]),
    ("setsymmetricdifference", [se(["a"]), se(["a"])]),
    ("setsymmetricdifference", [se([]), se(["a"])]),
    ("setsymmetricdifference", [se(["a"]), se(["b"]), se(["c"])]),
    ("sethaselement", [se(["a", "b"]), st("a")]),
    ("sethaselement", [se(["a", "b"]), st("z")]),
    ("sethaselement", [se([]), st("a")]),
    ("setproduct", [se(["a"]), se(["x"])]),
    ("setproduct", [se(["a", "b"]), se(["x", "y"])]),
    ("setproduct", [se(["a"]), se([])]),
    ("setproduct", [ls(["a", "b"]), ls(["x"])]),
    ("setproduct", [se(["a"])]),
    ("flatten", [ls(["a"])]),
    ("chunklist", [ls(["a", "b", "c"]), nm(2)]),
    ("length", [ls(["a", "b"])]),
    # The empty collection, for every function whose answer's *shape* turns on
    # it. Until 2026-08-17 sixteen collection functions had never been handed
    # one: the interesting part is usually the result type -- an empty result
    # still has to name an element type, and the two implementations derive it
    # by different routes.
    ("distinct", [ls([])]),
    ("compact", [ls([])]),
    ("concat", [ls([]), ls([])]),
    ("contains", [ls([]), st("a")]),
    ("element", [ls([]), nm(0)]),
    ("flatten", [ls([])]),
    ("length", [ls([])]),
    ("lookup", [mp({}), st("a"), st("z")]),
    ("reverselist", [ls([])]),
    ("setintersection", [se([]), se([])]),
    ("setsubtract", [se([]), se(["a"])]),
    ("slice", [ls([]), nm(0), nm(0)]),
    ("sort", [ls([])]),
    ("zipmap", [ls([]), ls([])]),
    ("chunklist", [ls([]), nm(2)]),
    # Containers holding an unknown element. Every row below was unreachable
    # until 2026-08-17 -- the container collapsed to a wholly unknown value on
    # construction, so these functions had never been driven with the ordinary
    # plan-time shape at all. A list's length is decided by its own structure;
    # a set's is not, because an unknown element may still resolve to a value
    # equal to another member, so go-cty answers with bounds rather than a count.
    ("length", [ls_uk("a", UK)]),
    ("length", [se_uk("z", UK)]),
    ("length", [se_uk(UK, UK)]),
    ("length", [se_uk(UK)]),
    ("length", [se_uk("a", "b", UK)]),
    ("contains", [ls_uk("a", UK), st("a")]),
    ("contains", [ls_uk("a", UK), st("zzz")]),
    ("contains", [se_uk("z", UK), st("z")]),
    ("contains", [se_uk("z", UK), st("zzz")]),
    ("distinct", [ls_uk("a", UK)]),
    ("distinct", [ls_uk(UK, UK)]),
    ("compact", [ls_uk("a", UK)]),
    ("join", [st("-"), ls_uk("a", UK)]),
    ("jsonencode", [ls_uk("a", UK)]),
    ("keys", [mp({"a": "1"})]),
    ("reverselist", [ls_uk("a", UK)]),
    ("concat", [ls_uk("a", UK), ls(["b"])]),
    ("slice", [ls_uk("a", UK), nm(0), nm(1)]),
    ("element", [ls_uk("a", UK), nm(0)]),
    ("element", [ls_uk("a", UK), nm(1)]),
    ("flatten", [ls_uk("a", UK)]),
    ("coalescelist", [ls_uk("a", UK), ls(["b"])]),
    ("chunklist", [ls_uk("a", UK), nm(1)]),
    ("zipmap", [ls(["a", "b"]), ls_uk("z", UK)]),
    ("setunion", [se_uk("z", UK), se(["q"])]),
    ("setintersection", [se_uk("z", UK), se(["z", "q"])]),
    ("sort", [ls_uk("a", UK)]),
    ("formatlist", [st("%s!"), ls_uk("a", UK)]),
    # A set holding an unknown element has an undecided *length* -- the unknown
    # may coalesce with a member -- so go-cty defers the whole list where a
    # list-typed argument only defers the affected rows. Both shapes measured
    # as divergences on 2026-08-17.
    ("formatlist", [st("<%s>"), se_uk("z", UK)]),
    ("formatlist", [st("%s%s"), ls_uk("a", UK), ls(["x", "y"])]),
    ("coalesce", [st(""), st("b")]),
    ("coalesce", [st("a"), st("b")]),
    ("coalescelist", [ls([]), ls(["a"])]),
    ("range", [nm(3)]),
    ("range", [nm(-3)]),
    ("range", [nm(0)]),
    ("range", [nm(1), nm(5)]),
    ("range", [nm(5), nm(1)]),
    ("range", [nm(1), nm(5), nm(2)]),
    ("range", [nm(5), nm(1), nm(-2)]),
    ("range", [nm(0), nm("1"), nm("0.25")]),
    ("range", [nm(1), nm(5), nm(-1)]),
    ("range", [nm(0), nm(2000)]),
    ("range", [nm(0), nm(10), nm(0)]),
    # encoding and time
    ("jsonencode", [ls(["a"])]),
    ("jsonencode", [nm(1)]),
    # jsonencode had four cases here, and its only known-value list case was
    # ["a"] -- a single element, which cannot show a separator. Go writes
    # `["a","b"]` and Python `["a", "b"]`; go sorts object keys and escapes
    # `<`, `>`, `&` while leaving non-ASCII alone, and Python does the reverse
    # on both. Every one of those lands in state and is compared as text.
    ("jsonencode", [ls(["a", "b"])]),
    ("jsonencode", [ob({"b": "x", "a": "y"})]),
    ("jsonencode", [mp({"z": "1", "a": "2"})]),
    ("jsonencode", [st("a<b>&c")]),
    ("jsonencode", [st("héllo")]),
    ("jsonencode", [st('a"b\\c')]),
    ("jsonencode", [nm("0.00001")]),
    ("jsonencode", [nm("1e21")]),
    # A number needing more significant digits than Decimal's default context
    # carries. Every string-producing route runs through the same renderer, and
    # exactly one row in the whole sweep held a number this long -- hasindex,
    # which answers a bool, so the digits never reached a string and the
    # truncation was invisible here while go-cty printed all of them.
    ("jsonencode", [nm(2**100)]),
    ("jsonencode", [bl(True)]),
    ("jsonencode", [ln(["1", "2"])]),
    ("jsondecode", [st('{"a":1}')]),
    ("jsondecode", [st("[1,2]")]),
    ("jsondecode", [st('[1,"a",true]')]),
    ("jsondecode", [st('{"a":{"b":[1,{"c":true}]}}')]),
    ("jsondecode", [st('{"a":null}')]),
    ("jsondecode", [st("null")]),
    ("jsondecode", [st("{}")]),
    ("csvdecode", [st("a,b\n1,2")]),
    ("csvdecode", [st("a,b\n1,2\n3,4")]),
    ("csvdecode", [st("a,b")]),
    ("csvdecode", [st("a,a\n1,2")]),
    ("csvdecode", [st("a,b\n1")]),
    ("timeadd", [st("2020-01-01T00:00:00Z"), st("1h")]),
    ("timeadd", [st("2020-01-01T00:00:00+02:00"), st("1h30m")]),
    ("timeadd", [st("2020-01-01T00:00:00Z"), st("-2h5m")]),
    ("timeadd", [st("2020-01-01T00:00:00Z"), st("not a duration")]),
    # The ends of the range, where Go's time.Time keeps going and Python's
    # datetime stops. Recorded divergences, not agreements -- see KNOWN_DIVERGENCES.
    ("timeadd", [st("9999-12-31T23:59:59Z"), st("1h")]),
    ("timeadd", [st("0001-01-01T00:00:00Z"), st("-1s")]),
    # The duration overflow boundary, where the two *do* agree: Go's
    # time.Duration is int64 nanoseconds, and this package's parser enforces the
    # same limit rather than inheriting timedelta's much wider one.
    ("timeadd", [st("2026-01-01T00:00:00Z"), st("2560000h")]),
    ("timeadd", [st("2026-01-01T00:00:00Z"), st("2570000h")]),
    ("formatdate", [st("YYYY-MM-DD"), st("2020-01-02T03:04:05Z")]),
    ("formatdate", [st("EEEE, DD MMMM YYYY hh:mm:ss ZZZZ"), st("2020-01-02T03:04:05Z")]),
    ("formatdate", [st("HH:mm aa Z"), st("2020-11-22T13:04:05-08:00")]),
    ("formatdate", [st("'it''s' YYYY"), st("2020-01-02T03:04:05Z")]),
    ("formatdate", [st("YYY"), st("2020-01-02T03:04:05Z")]),
    # A Go reference layout, which go-cty returns as literal text and this
    # package refuses. The one place it declines something go-cty answers --
    # see KNOWN_DIVERGENCES for why. The quoted form is the escape, and agrees.
    ("formatdate", [st("2006-01-02"), st("2020-01-02T03:04:05Z")]),
    ("formatdate", [st("'2006-01-02'"), st("2020-01-02T03:04:05Z")]),
    ("formatdate", [st("2006"), st("2020-01-02T03:04:05Z")]),
    # An infinite number through every verb that renders one. go-cty spells it
    # `+Inf` -- `big.Float.Text`'s answer -- where `str(Decimal)` says
    # "Infinity", and the float verbs drop the zero flag for it while `%v` and
    # `%s` keep it, because only the former delegate to Go's own fmt.
    ("format", [st("%v"), nm_inf()]),
    ("format", [st("%f"), nm_inf()]),
    ("format", [st("%e"), nm_inf()]),
    ("format", [st("%g"), nm_inf()]),
    ("format", [st("%s"), nm_inf()]),
    ("format", [st("%08.2f"), nm_inf()]),
    ("format", [st("%08v"), nm_inf()]),
    ("format", [st("%10.2f"), nm_inf()]),
    ("format", [st("% f"), nm_inf()]),
    ("format", [st("%v"), nm_inf(negative=True)]),
    ("format", [st("%f"), nm_inf(negative=True)]),
    ("format", [st("% f"), nm_inf(negative=True)]),
    ("format", [st("%d"), nm_inf()]),
    ("format", [st("%#v"), nm_inf()]),
    ("formatdate", [st("YYYY"), st("2020-01-02 03:04:05Z")]),
    # format
    ("format", [st("%s"), st("hi")]),
    ("format", [st("%s"), nm(2**100)]),
    ("format", [st("%q"), st('a"b')]),
    ("format", [st("%v"), st("hi")]),
    ("format", [st("%v"), nm(42)]),
    # %v is the default verb and picks between %e and %f on a threshold Go fixes
    # at 6 regardless of how many digits it is about to print. Deriving it from
    # the value's own significant digits rendered every round number
    # exponentially -- 10 as "1e+01" -- and 1234567 non-exponentially.
    ("format", [st("%v"), nm(10)]),
    ("format", [st("%v"), nm(100)]),
    ("format", [st("%v"), nm(1500)]),
    ("format", [st("%v"), nm(250000)]),
    ("format", [st("%v"), nm(1234567)]),
    ("format", [st("%v"), nm(12345678)]),
    # Integer flags: precision and the alternate form were parsed and never
    # read, and `-` did not cancel zero-padding, so %-05d of 42 gave "42000".
    ("format", [st("%-05d"), nm(42)]),
    ("format", [st("%0-5d"), nm(42)]),
    ("format", [st("%-08d"), nm(42)]),
    ("format", [st("%.5d"), nm(42)]),
    ("format", [st("%05.2d"), nm(42)]),
    ("format", [st("%.5x"), nm(42)]),
    ("format", [st("%-05x"), nm(255)]),
    ("format", [st("%#x"), nm(42)]),
    ("format", [st("%#X"), nm(255)]),
    ("format", [st("%#o"), nm(42)]),
    ("format", [st("%#b"), nm(42)]),
    ("format", [st("%10t"), bl(True)]),
    ("format", [st("%-10t"), bl(False)]),
    ("format", [st("%v"), nm("0.00001")]),
    ("format", [st("%#v"), nm("0.00001")]),
    ("format", [st("%#v"), ls(["a", "b"])]),
    ("format", [st("%v"), ln(["0.00001"])]),
    ("format", [st("%v"), mp({"z": "1", "a": "2"})]),
    ("format", [st("%v"), ob({"b": "2", "a": "1"})]),
    ("format", [st("%v"), se(["b", "a"])]),
    ("format", [st("%.1e"), nm("9.99")]),
    ("format", [st("%+.1f"), nm("1.5")]),
    ("format", [st("% .1f"), nm("1.5")]),
    ("format", [st("%.0g"), nm(123)]),
    ("format", [st("%t"), bl(True)]),
    ("format", [st("%d"), nm(42)]),
    ("format", [st("%d"), nm("1.5")]),
    ("format", [st("%b"), nm(5)]),
    ("format", [st("%o"), nm(64)]),
    ("format", [st("%x"), nm(255)]),
    ("format", [st("%X"), nm(255)]),
    ("format", [st("%e"), nm(42)]),
    ("format", [st("%E"), nm("0.00001")]),
    ("format", [st("%f"), nm("3.14159")]),
    ("format", [st("%g"), nm("0.00001")]),
    ("format", [st("%G"), nm("1e21")]),
    ("format", [st("%5s|"), st("ab")]),
    ("format", [st("%-5s|"), st("ab")]),
    ("format", [st("%.2s"), st("hello")]),
    ("format", [st("%05d"), nm(42)]),
    ("format", [st("%+d"), nm(42)]),
    ("format", [st("%08.2f"), nm(-42)]),
    ("format", [st("%.3e"), nm(0)]),
    ("format", [st("%.5g"), nm("0.00001")]),
    ("format", [st("100%%")]),
    ("format", [st("a%sb"), st("x")]),
    ("format", [st("%s%s"), st("a"), st("b")]),
    ("format", [st("%[2]s%[1]s"), st("a"), st("b")]),
    ("format", [st("%s"), st("a"), st("b")]),
    ("format", [st("hi"), st("a")]),
    ("format", [st("%s%s"), st("a")]),
    ("format", [st("%z"), st("a")]),
    ("format", [st("%5s|"), st("\U0001f468\u200d\U0001f469\u200d\U0001f467")]),
    ("format", [st("%.1s"), st("\U0001f468\u200d\U0001f469\u200d\U0001f467")]),
    ("format", [st("%d"), st("nope")]),
    ("format", [st("%s"), nul("string", CtyString())]),
    ("format", [st("%v"), nul("string", CtyString())]),
    ("formatlist", [st("%s"), ls(["a", "b"])]),
    ("formatlist", [st("%s-%s"), ls(["a", "b"]), st("x")]),
    ("formatlist", [st("%s%s"), ls(["a", "b"]), ls(["1", "2"])]),
    ("formatlist", [st("%s%s"), ls(["a", "b"]), ls(["1"])]),
    ("formatlist", [st("%s"), ls([])]),
    ("formatlist", [st("%s"), st("a")]),
    ("formatlist", [st("hi")]),
    ("formatlist", [st("<%s>"), se(["a", "b"])]),
    # bytes
    ("byteslen", [by(b"hello world")]),
    ("byteslen", [by(b"")]),
    ("bytesslice", [by(b"hello world"), nm(0), nm(11)]),
    ("bytesslice", [by(b"hello world"), nm(0), nm(0)]),
    ("bytesslice", [by(b"hello world"), nm(1), nm(3)]),
    ("bytesslice", [by(b"hello world"), nm(6), nm(5)]),
    ("bytesslice", [by(b"hello world"), nm(9), nm(5)]),
    ("bytesslice", [by(b"hello world"), nm(-1), nm(2)]),
    ("bytesslice", [by(b"hello world"), nm(1), nm(-2)]),
    # conversion
    ("tostring", [st("a")]),
    ("tostring", [nm(1)]),
    ("tostring", [nm("1.5")]),
    ("tostring", [nm(2**100)]),
    ("tostring", [nm("1.2345678901234567890123456789")]),
    ("tostring", [nm("-0.0")]),
    ("tostring", [bl(True)]),
    ("tostring", [bl(False)]),
    ("tostring", [ls(["a"])]),
    ("tostring", [nul("string", CtyString())]),
    ("tonumber", [nm(1)]),
    ("tonumber", [st("1.5")]),
    ("tonumber", [st("abc")]),
    ("tonumber", [bl(True)]),
    ("tonumber", [ls(["a"])]),
    ("tonumber", [nul("number", CtyNumber())]),
    ("tostring", [nm("1e2")]),
    ("tostring", [nm("1e-7")]),
    ("tostring", [nm("1.50")]),
    ("tobool", [bl(True)]),
    ("tobool", [st("true")]),
    ("tobool", [st("false")]),
    ("tobool", [st("yes")]),
    ("tobool", [st("TRUE")]),
    ("tobool", [st("True")]),
    ("tobool", [st("1")]),
    ("tobool", [st("0")]),
    ("tobool", [nm(1)]),
    ("tobool", [nul("bool", CtyBool())]),
    ("setproduct", [se(["a"]), ls(["x"])]),
    ("setproduct", [ls(["a", "b"]), ls(["x", "y"])]),
]

# 🌊🪢🔚
