"""
Performs cross-language compatibility tests by deserializing canonical
fixtures generated by the reference `go-cty` implementation.
"""
from decimal import Decimal
from pathlib import Path

import pytest

from pyvider.cty import (
    CtyBool, CtyDynamic, CtyList, CtyMap, CtyNumber, CtyObject, CtySet,
    CtyString, CtyTuple, CtyValue, convert, unify
)
from pyvider.cty.codec import cty_from_msgpack
from pyvider.cty.exceptions import CtyConversionError
from pyvider.cty.values.markers import RefinedUnknownValue

fset = frozenset

EXPECTED_RESULTS = {
    "string_simple": {"type": CtyString(), "value": "hello world"},
    "number_simple": {"type": CtyNumber(), "value": Decimal("42")},
    "bool_true": {"type": CtyBool(), "value": True},
    "large_number": {"type": CtyNumber(), "value": Decimal(2**100)},
    "null_string": {"type": CtyString(), "is_null": True},
    "unknown_unrefined": {"type": CtyString(), "is_unknown": True},
    "unknown_refined_str": { "type": CtyString(), "is_unknown": True, "value": RefinedUnknownValue(string_prefix="start-") },
    "unknown_refined_num": { "type": CtyNumber(), "is_unknown": True, "value": RefinedUnknownValue(number_lower_bound=(Decimal("100"), True), number_upper_bound=(Decimal("200"), False)) },
    "unknown_refined_list": { "type": CtyList(element_type=CtyString()), "is_unknown": True, "value": RefinedUnknownValue(collection_length_lower_bound=3, collection_length_upper_bound=3) },
    "list_of_strings": { "type": CtyList(element_type=CtyString()), "value": (CtyString().validate("a"), CtyString().validate("b")) },
    "set_of_numbers": { "type": CtySet(element_type=CtyNumber()), "value": fset([CtyNumber().validate(1), CtyNumber().validate(2)]) },
    "map_simple": { "type": CtyMap(element_type=CtyBool()), "value": {"a": CtyBool().validate(True), "b": CtyBool().validate(False)} },
    "set_of_tuples": { "type": CtySet(element_type=CtyTuple(element_types=(CtyString(), CtyNumber()))), "value": fset([CtyTuple(element_types=(CtyString(), CtyNumber())).validate(("a", 1)), CtyTuple(element_types=(CtyString(), CtyNumber())).validate(("b", 2))]) },
    "deeply_nested_object": {
        "type": CtyObject({"id": CtyString(), "enabled": CtyBool(), "ports": CtyList(element_type=CtyNumber()), "config": CtyObject({"retries": CtyNumber(), "params": CtyMap(element_type=CtyString())}), "metadata": CtyMap(element_type=CtyString()), "extra": CtyString()}, optional_attributes={"metadata"}),
        "value": { "id": CtyString().validate("obj1"), "enabled": CtyBool().validate(True), "ports": CtyList(element_type=CtyNumber()).validate([80, 443]), "config": CtyObject({"retries": CtyNumber(), "params": CtyMap(element_type=CtyString())}).validate({"retries": 3, "params": {"timeout": "5s"}}), "metadata": CtyValue.null(CtyMap(element_type=CtyString())), "extra": CtyValue.unknown(CtyString()) },
    },
    "dynamic_wrapped_string": {"type": CtyDynamic(), "value": CtyString().validate("dynamic")},
    "dynamic_wrapped_object": { "type": CtyDynamic(), "value": CtyObject({"key": CtyString()}).validate({"key": "value"}) },
    "advanced_capsule": {"type": CtyDynamic(), "is_null": True},
}

def deep_value_equal(a: CtyValue, b: CtyValue) -> bool:
    if not a.type.equal(b.type) or a.is_null != b.is_null or a.is_unknown != b.is_unknown: return False
    if a.is_null or a.is_unknown: return True
    val_a, val_b = a.value, b.value
    if isinstance(val_a, dict) and isinstance(val_b, dict): return val_a.keys() == val_b.keys() and all(deep_value_equal(val_a[k], val_b[k]) for k in val_a)
    if isinstance(val_a, tuple) and isinstance(val_b, tuple): return len(val_a) == len(val_b) and all(deep_value_equal(val_a[i], val_b[i]) for i in range(len(val_a)))
    if isinstance(val_a, frozenset) and isinstance(val_b, frozenset): return len(val_a) == len(val_b) and all(any(deep_value_equal(item_a, item_b) for item_b in val_b) for item_a in val_a)
    return val_a == val_b

@pytest.mark.parametrize("fixture_name", EXPECTED_RESULTS.keys())
def test_msgpack_deserialization_from_go_cty(fixture_name: str, go_fixtures: Path):
    """
    Reads a MessagePack fixture generated by go-cty and verifies that
    pyvider.cty can deserialize it into the correct CtyValue.
    """
    expected_spec = EXPECTED_RESULTS[fixture_name]
    expected_type = expected_spec["type"]
    
    fixture_path = go_fixtures / f"{fixture_name}.msgpack"
    packed_bytes = fixture_path.read_bytes()
    deserialized_val = cty_from_msgpack(packed_bytes, expected_type)

    # --- DEFINITIVE FIX: Corrected test logic flow ---
    if expected_spec.get("is_null", False):
        assert deserialized_val.is_null
        # For dynamic nulls, the type might be dynamic, which is okay.
        if not isinstance(expected_type, CtyDynamic):
            assert deserialized_val.type.equal(expected_type)
        return # Test is complete for null values

    if expected_spec.get("is_unknown", False):
        assert deserialized_val.is_unknown
        assert deserialized_val.type.equal(expected_type)
        if "value" in expected_spec:
            assert deserialized_val.value == expected_spec["value"]
        return # Test is complete for unknown values

    # If we reach here, the value is known and not null.
    assert not deserialized_val.is_unknown and not deserialized_val.is_null
    
    expected_value_obj = expected_spec["value"]
    
    # For dynamic types, the expected value is a CtyValue, and the deserialized
    # value's type will be the inner, concrete type.
    if isinstance(expected_type, CtyDynamic):
        assert deserialized_val.type.equal(expected_value_obj.type)
        assert deep_value_equal(deserialized_val, expected_value_obj)
    else:
        assert deserialized_val.type.equal(expected_type)
        expected_cty_value = CtyValue(expected_type, expected_value_obj)
        assert deep_value_equal(deserialized_val, expected_cty_value)

def test_unification_with_deserialized_types(go_fixtures: Path):
    type1 = EXPECTED_RESULTS["deeply_nested_object"]["type"]
    type2 = EXPECTED_RESULTS["map_simple"]["type"]
    unified = unify([type1, type2])
    assert unified.equal(CtyDynamic())

def test_conversion_with_deserialized_types(go_fixtures: Path):
    val = cty_from_msgpack((go_fixtures / "number_simple.msgpack").read_bytes(), CtyNumber())
    converted = convert(val, CtyString())
    assert converted.type.equal(CtyString()) and converted.value == "42"
