"""
Performs cross-language compatibility tests by deserializing canonical
fixtures generated by the reference `go-cty` implementation.
"""
import operator
from decimal import Decimal
from pathlib import Path

import pytest

from pyvider.cty import (
    CtyBool,
    CtyDynamic,
    CtyList,
    CtyMap,
    CtyNumber,
    CtyObject,
    CtySet,
    CtyString,
    CtyTuple,
    CtyType,
    CtyValue,
    convert,
    unify,
)
from pyvider.cty.codec import cty_from_msgpack
from pyvider.cty.exceptions import CtyConversionError
from pyvider.cty.values.markers import RefinedUnknownValue

# Path to the directory where the Go program saved the fixtures.
FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "go-cty"

# A helper to create a frozenset for set comparisons
fset = frozenset

# Define the expected Python-side representation for each fixture.
# This acts as the "expected" result for our assertions.
EXPECTED_RESULTS = {
    "string_simple": {"type": CtyString(), "value": "hello world"},
    "number_simple": {"type": CtyNumber(), "value": Decimal("42")},
    "bool_true": {"type": CtyBool(), "value": True},
    "large_number": {"type": CtyNumber(), "value": Decimal(2**100)},
    "null_string": {"type": CtyString(), "is_null": True},
    "unknown_unrefined": {"type": CtyString(), "is_unknown": True},
    "unknown_refined_str": {
        "type": CtyString(),
        "is_unknown": True,
        "value": RefinedUnknownValue(string_prefix="start-"),
    },
    "unknown_refined_num": {
        "type": CtyNumber(),
        "is_unknown": True,
        # FIX: Use the correct keyword arguments for the RefinedUnknownValue constructor.
        "value": RefinedUnknownValue(
            lower_bound=(Decimal("100"), True), upper_bound=(Decimal("200"), False)
        ),
    },
    "unknown_refined_list": {
        "type": CtyList(CtyString()),
        "is_unknown": True,
        # FIX: Use the correct keyword arguments for the RefinedUnknownValue constructor.
        "value": RefinedUnknownValue(min_length=3, max_length=3),
    },
    "list_of_strings": {
        "type": CtyList(CtyString()),
        "value": (CtyString().validate("a"), CtyString().validate("b")),
    },
    "set_of_numbers": {
        "type": CtySet(CtyNumber()),
        "value": fset([CtyNumber().validate(1), CtyNumber().validate(2)]),
    },
    "map_simple": {
        "type": CtyMap(CtyBool()),
        "value": {"a": CtyBool().validate(True), "b": CtyBool().validate(False)},
    },
    "set_of_tuples": {
        "type": CtySet(CtyTuple([CtyString(), CtyNumber()])),
        "value": fset([
            CtyTuple([CtyString(), CtyNumber()]).validate(("a", 1)),
            CtyTuple([CtyString(), CtyNumber()]).validate(("b", 2)),
        ]),
    },
    "deeply_nested_object": {
        "type": CtyObject({
            "id": CtyString(), "enabled": CtyBool(), "ports": CtyList(CtyNumber()),
            "config": CtyObject({"retries": CtyNumber(), "params": CtyMap(CtyString())}),
            "metadata": CtyMap(CtyString()), "extra": CtyString(),
        }),
        "value": {
            "id": CtyString().validate("obj1"),
            "enabled": CtyBool().validate(True),
            "ports": CtyList(CtyNumber()).validate([80, 443]),
            "config": CtyObject({"retries": CtyNumber(), "params": CtyMap(CtyString())}).validate({
                "retries": 3, "params": {"timeout": "5s"}
            }),
            "metadata": CtyValue.null(CtyMap(CtyString())),
            "extra": CtyValue.unknown(CtyString()),
        },
    },
    "dynamic_wrapped_string": {"type": CtyDynamic(), "value": CtyString().validate("dynamic")},
    "dynamic_wrapped_object": {
        "type": CtyDynamic(),
        "value": CtyObject({"key": CtyString()}).validate({"key": "value"}),
    },
    "advanced_capsule": {"type": CtyDynamic(), "is_null": True},
}


def deep_value_equal(a: CtyValue, b: CtyValue) -> bool:
    """A more robust helper for recursive equality checks."""
    if not a.type.equal(b.type) or a.is_null != b.is_null or a.is_unknown != b.is_unknown:
        return False
    if a.is_null or a.is_unknown:
        return True

    val_a, val_b = a.value, b.value
    if isinstance(val_a, dict) and isinstance(val_b, dict):
        if val_a.keys() != val_b.keys():
            return False
        return all(deep_value_equal(val_a[k], val_b[k]) for k in val_a)
    if isinstance(val_a, tuple) and isinstance(val_b, tuple):
        if len(val_a) != len(val_b):
            return False
        return all(deep_value_equal(val_a[i], val_b[i]) for i in range(len(val_a)))
    if isinstance(val_a, frozenset) and isinstance(val_b, frozenset):
        if len(val_a) != len(val_b):
            return False
        # For sets of complex types, simple equality might fail.
        # Create sorted lists of string representations for comparison.
        sorted_a = sorted([str(item) for item in val_a])
        sorted_b = sorted([str(item) for item in val_b])
        return sorted_a == sorted_b

    return val_a == val_b


@pytest.fixture(scope="session", params=list(EXPECTED_RESULTS.keys()))
def go_fixture(request):
    """A session-scoped fixture that loads each go-cty fixture file once."""
    fixture_name = request.param
    if not FIXTURE_DIR.exists():
        pytest.skip("Go-cty fixture directory not found. Run the generation script.")

    expected_spec = EXPECTED_RESULTS[fixture_name]
    expected_type = expected_spec["type"]

    fixture_path = FIXTURE_DIR / f"{fixture_name}.msgpack"
    if not fixture_path.exists():
        pytest.skip(f"Fixture file not found: {fixture_path}")

    packed_bytes = fixture_path.read_bytes()
    deserialized_val = cty_from_msgpack(packed_bytes, expected_type)
    return fixture_name, deserialized_val, expected_spec


class TestGoCtyDeserialization:
    def test_msgpack_deserialization_from_go_cty(self, go_fixture):
        """
        Reads a MessagePack fixture generated by go-cty and verifies that
        pyvider.cty can deserialize it into the correct CtyValue.
        """
        fixture_name, deserialized_val, expected_spec = go_fixture
        expected_type = expected_spec["type"]

        assert deserialized_val.type.equal(expected_type)

        if expected_spec.get("is_unknown", False):
            assert deserialized_val.is_unknown
            if "value" in expected_spec:
                assert deserialized_val.value == expected_spec["value"]
        elif expected_spec.get("is_null", False):
            assert deserialized_val.is_null
        else:
            assert not deserialized_val.is_unknown and not deserialized_val.is_null
            expected_value = CtyValue(expected_type, expected_spec["value"])
            assert deep_value_equal(deserialized_val, expected_value)


class TestUnificationWithGoFixtures:
    """Comprehensive tests for `unify` using deserialized go-cty types."""

    @pytest.mark.parametrize(
        "type_names, expected_unified_type_str",
        [
            (["string_simple", "number_simple"], "dynamic"),
            (["list_of_strings", "list_of_strings"], "list<string>"),
            (["set_of_numbers", "list_of_strings"], "dynamic"),
            (["object_simple", "deeply_nested_object"], "dynamic"),
            (["map_simple", "object_simple"], "dynamic"),
            (["unknown_refined_list", "list_of_strings"], "list<string>"),
            (["set_of_tuples", "set_of_tuples"], "set<tuple<string, number>>"),
            (["unknown_refined_str", "unknown_refined_num"], "dynamic"),
        ],
    )
    def test_unification_scenarios(self, type_names, expected_unified_type_str):
        types_to_unify = [EXPECTED_RESULTS[name]["type"] for name in type_names]
        unified_type = unify(types_to_unify)
        
        assert str(unified_type) == expected_unified_type_str


class TestConversionWithGoFixtures:
    """Comprehensive tests for `convert` using deserialized go-cty values."""

    def test_convert_number_to_string(self):
        packed_bytes = (FIXTURE_DIR / "number_simple.msgpack").read_bytes()
        val = cty_from_msgpack(packed_bytes, CtyNumber())
        
        converted = convert(val, CtyString())
        assert converted.type.equal(CtyString())
        assert converted.value == "42"

    def test_convert_list_to_set(self):
        packed_bytes = (FIXTURE_DIR / "list_of_strings.msgpack").read_bytes()
        val = cty_from_msgpack(packed_bytes, CtyList(CtyString()))

        converted = convert(val, CtySet(CtyString()))
        assert converted.type.equal(CtySet(CtyString()))
        assert converted.value == fset([CtyString().validate("a"), CtyString().validate("b")])

    def test_convert_unknown_to_string(self):
        packed_bytes = (FIXTURE_DIR / "unknown_unrefined.msgpack").read_bytes()
        val = cty_from_msgpack(packed_bytes, CtyString())

        converted = convert(val, CtyString())
        assert converted.type.equal(CtyString())
        assert converted.is_unknown

    def test_impossible_conversion_raises_error(self):
        packed_bytes = (FIXTURE_DIR / "string_simple.msgpack").read_bytes()
        val = cty_from_msgpack(packed_bytes, CtyString())

        with pytest.raises(CtyConversionError):
            convert(val, CtyNumber())
