"""
Generates canonical MessagePack fixtures and a JSON manifest from pyvider.cty.
This script is the "source of truth" for the reverse compatibility test.
"""
import argparse
import json
from decimal import Decimal
from pathlib import Path
from typing import Any

from pyvider.cty import (
    CtyBool, CtyDynamic, CtyList, CtyMap, CtyNumber, CtyObject, CtySet,
    CtyString, CtyTuple, CtyValue
)
from pyvider.cty.codec import cty_to_msgpack
from pyvider.cty.conversion import encode_cty_type_to_wire_json
from pyvider.cty.values.markers import RefinedUnknownValue

# A helper to create a frozenset for set comparisons
fset = frozenset

def get_test_cases() -> dict[str, CtyValue]:
    """Defines all canonical test cases to be generated by Python."""
    # This tuple type is used in the set_of_tuples case
    tuple_type = CtyTuple(element_types=(CtyString(), CtyNumber()))

    return {
        "string_simple": CtyString().validate("hello from python"),
        "number_simple": CtyNumber().validate(12345),
        "bool_true": CtyBool().validate(True),
        "large_number": CtyNumber().validate(Decimal(2**128)),
        "null_string": CtyValue.null(CtyString()),
        "unknown_unrefined": CtyValue.unknown(CtyNumber()),
        "unknown_refined_str": CtyValue.unknown(
            CtyString(), value=RefinedUnknownValue(string_prefix="py-")
        ),
        "unknown_refined_list": CtyValue.unknown(
            CtyList(element_type=CtyString()),
            value=RefinedUnknownValue(collection_length_lower_bound=1, collection_length_upper_bound=5),
        ),
        "list_of_strings": CtyList(element_type=CtyString()).validate(["py-a", "py-b"]),
        "set_of_numbers": CtySet(element_type=CtyNumber()).validate({100, 200, 300}),
        "map_simple": CtyMap(element_type=CtyBool()).validate({"py_a": True, "py_b": False}),
        "set_of_tuples": CtySet(element_type=tuple_type).validate([("a", 1), ("b", 2)]),
        "deeply_nested_object": CtyObject(
            {
                "id": CtyString(), "ports": CtyList(element_type=CtyNumber()),
                "config": CtyObject({"params": CtyMap(element_type=CtyString())}),
                "metadata": CtyMap(element_type=CtyString()),
            },
            optional_attributes={"metadata"},
        ).validate({
            "id": "py-obj1", "ports": [8080, 8443],
            "config": {"params": {"timeout": "10s"}},
            "metadata": None,
        }),
        "dynamic_wrapped_string": CtyDynamic().validate("dynamic from python"),
        "dynamic_wrapped_object": CtyDynamic().validate(
            CtyObject({"key": CtyString()}).validate({"key": "py-value"})
        ),
    }

def cty_to_manifest_native(value: CtyValue) -> Any:
    """Converts a CtyValue to a native Python type suitable for the JSON manifest."""
    if value.is_null or value.is_unknown:
        return None
    
    # If the value is dynamic, recurse on its inner value
    if isinstance(value.type, CtyDynamic):
        return cty_to_manifest_native(value.value)

    val = value.value
    if isinstance(val, Decimal):
        return str(val)
    if isinstance(val, tuple | frozenset):
        return [cty_to_manifest_native(item) for item in val]
    if isinstance(val, dict):
        return {k: cty_to_manifest_native(v) for k, v in val.items()}
    
    return val

def main():
    parser = argparse.ArgumentParser(description="Generate pyvider.cty test fixtures.")
    parser.add_argument("-d", "--directory", required=True, type=Path, help="Directory to write fixtures and manifest.")
    args = parser.parse_args()

    output_dir: Path = args.directory
    output_dir.mkdir(parents=True, exist_ok=True)

    test_cases = get_test_cases()
    manifest = {}

    for name, value in test_cases.items():
        # 1. Serialize the CtyValue to a .msgpack file
        msgpack_bytes = cty_to_msgpack(value, value.type)
        (output_dir / f"{name}.msgpack").write_bytes(msgpack_bytes)

        # 2. Create the manifest entry for this value
        manifest[name] = {
            "type": encode_cty_type_to_wire_json(value.type),
            "value": cty_to_manifest_native(value),
            "isUnknown": value.is_unknown,
            "isNull": value.is_null,
        }

    # 3. Write the complete manifest file
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"✅ Successfully generated {len(test_cases)} fixtures and manifest.json in {output_dir}")

if __name__ == "__main__":
    main()
