"""
Generates a comprehensive set of canonical .msgpack fixture files using
the pyvider.cty library for verification by the go-cty implementation.
"""
import sys
from decimal import Decimal
from pathlib import Path

from pyvider.cty import (
    CtyBool, CtyDynamic, CtyList, CtyMap, CtyNumber, CtyObject, CtySet,
    CtyString, CtyTuple, CtyValue
)
from pyvider.cty.codec import cty_to_msgpack
from pyvider.cty.values.markers import RefinedUnknownValue

# A helper to create a frozenset for set values
fset = frozenset

# Define all canonical test cases to be generated by Python
TEST_CASES = {
    "string_simple": CtyString().validate("hello world"),
    "number_simple": CtyNumber().validate(42),
    "bool_true": CtyBool().validate(True),
    "large_number": CtyNumber().validate(2**100),
    "null_string": CtyValue.null(CtyString()),
    "unknown_unrefined": CtyValue.unknown(CtyString()),
    "unknown_refined_str": CtyValue.unknown(
        CtyString(), value=RefinedUnknownValue(string_prefix="start-")
    ),
    "unknown_refined_num": CtyValue.unknown(
        CtyNumber(),
        value=RefinedUnknownValue(
            number_lower_bound=(Decimal("100"), True),
            number_upper_bound=(Decimal("200"), False),
        ),
    ),
    "unknown_refined_list": CtyValue.unknown(
        CtyList(element_type=CtyString()),
        value=RefinedUnknownValue(collection_length_lower_bound=3, collection_length_upper_bound=3),
    ),
    "list_of_strings": CtyList(element_type=CtyString()).validate(["a", "b"]),
    "set_of_numbers": CtySet(element_type=CtyNumber()).validate({1, 2}),
    "map_simple": CtyMap(element_type=CtyBool()).validate({"a": True, "b": False}),
    "set_of_tuples": CtySet(element_type=CtyTuple(element_types=(CtyString(), CtyNumber()))).validate(
        {("a", 1), ("b", 2)}
    ),
    "deeply_nested_object": CtyObject(
        attribute_types={
            "id": CtyString(), "enabled": CtyBool(), "ports": CtyList(element_type=CtyNumber()),
            "config": CtyObject({"retries": CtyNumber(), "params": CtyMap(element_type=CtyString())}),
            "metadata": CtyMap(element_type=CtyString()), "extra": CtyString(),
        },
        optional_attributes={"metadata"}
    ).validate({
        "id": "obj1", "enabled": True, "ports": [80, 443],
        "config": {"retries": 3, "params": {"timeout": "5s"}},
        "metadata": None,
        "extra": CtyValue.unknown(CtyString()),
    }),
    "dynamic_wrapped_string": CtyDynamic().validate("dynamic"),
    "dynamic_wrapped_object": CtyDynamic().validate(
        CtyObject({"key": CtyString()}).validate({"key": "value"})
    ),
}

def main(output_dir_str: str) -> None:
    output_dir = Path(output_dir_str)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"ℹ️  Generating fixtures in: {output_dir.resolve()}")

    for name, value in TEST_CASES.items():
        try:
            packed_bytes = cty_to_msgpack(value, value.type)
            fixture_path = output_dir / f"{name}.msgpack"
            fixture_path.write_bytes(packed_bytes)
            print(f"  - Wrote {fixture_path.name}")
        except Exception as e:
            print(f"🔥 Failed to generate fixture for '{name}': {e}", file=sys.stderr)
            sys.exit(1)

    print("✅ Fixture generation complete.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python generate_fixtures.py <output_directory>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
