from .markers import UNREFINED_UNKNOWN as UNREFINED_UNKNOWN
from attrs import define, field
from collections.abc import Iterator
from pyvider.cty.types import CtyType as CtyType
from typing import Any, Self, TypeVar

T = TypeVar('T', covariant=True)

@define(frozen=True, slots=True)
class CtyValue[T]:
    vtype: CtyType[T] = field()
    value: object | None = field(default=None)
    is_unknown: bool = field(default=False)
    is_null: bool = field(default=False)
    marks: frozenset[Any] = field(factory=frozenset)
    key_mapping: dict[str, CtyValue[Any]] = field(factory=dict)
    def __attrs_post_init__(self) -> None: ...
    @property
    def type(self) -> CtyType[T]: ...
    @property
    def raw_value(self) -> object | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __contains__(self, item: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> CtyValue[Any]: ...
    def __hash__(self) -> int: ...
    def has_mark(self, mark: object) -> bool: ...
    def mark(self, mark: object) -> Self: ...
    def with_marks(self, marks_to_add: set[Any]) -> Self: ...
    def unmark(self) -> tuple[Self, frozenset[Any]]: ...
    def is_true(self) -> bool: ...
    def is_false(self) -> bool: ...
    def is_empty(self) -> bool: ...
    @classmethod
    def unknown(cls, vtype: CtyType[Any], value: Any = ...) -> CtyValue[Any]: ...
    @classmethod
    def null(cls, vtype: CtyType[Any]) -> CtyValue[Any]: ...
