from _typeshed import Incomplete
from attrs import define
from decimal import Decimal

class UnknownValue: ...
class UnrefinedUnknownValue(UnknownValue): ...

@define(frozen=True, slots=True, auto_attribs=True, match_args=True)
class RefinedUnknownValue(UnknownValue):
    is_known_null: bool | None = ...
    string_prefix: str | None = ...
    number_lower_bound: tuple[Decimal, bool] | None = ...
    number_upper_bound: tuple[Decimal, bool] | None = ...
    collection_length_lower_bound: int | None = ...
    collection_length_upper_bound: int | None = ...

UNREFINED_UNKNOWN: Incomplete
