from pyvider.cty import CtyBool as CtyBool, CtyDynamic as CtyDynamic, CtyList as CtyList, CtyMap as CtyMap, CtyNumber as CtyNumber, CtySet as CtySet, CtyString as CtyString, CtyTuple as CtyTuple, CtyType as CtyType, CtyValue as CtyValue
from pyvider.cty.exceptions import CtyFunctionError as CtyFunctionError
from typing import Any

def distinct(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def flatten(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def sort(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def length(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def slice(input_val: CtyValue[Any], start_val: CtyValue[Any], end_val: CtyValue[Any]) -> CtyValue[Any]: ...
def concat(*lists: CtyValue[Any]) -> CtyValue[Any]: ...
def contains(collection: CtyValue[Any], value: CtyValue[Any]) -> CtyValue[Any]: ...
def keys(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def values(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
