from pyvider.cty import CtyBool as CtyBool, CtyNumber as CtyNumber, CtyString as CtyString, CtyValue as CtyValue
from pyvider.cty.exceptions import CtyFunctionError as CtyFunctionError
from typing import Any

def to_string(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def to_number(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def to_bool(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
