from pyvider.cty import CtyNumber as CtyNumber, CtyString as CtyString, CtyValue as CtyValue
from pyvider.cty.exceptions import CtyFunctionError as CtyFunctionError
from typing import Any

def add(a: CtyValue[Any], b: CtyValue[Any]) -> CtyValue[Any]: ...
def subtract(a: CtyValue[Any], b: CtyValue[Any]) -> CtyValue[Any]: ...
def multiply(a: CtyValue[Any], b: CtyValue[Any]) -> CtyValue[Any]: ...
def divide(a: CtyValue[Any], b: CtyValue[Any]) -> CtyValue[Any]: ...
def modulo(a: CtyValue[Any], b: CtyValue[Any]) -> CtyValue[Any]: ...
def negate(a: CtyValue[Any]) -> CtyValue[Any]: ...
def abs_fn(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def ceil_fn(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def floor_fn(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def log_fn(num_val: CtyValue[Any], base_val: CtyValue[Any]) -> CtyValue[Any]: ...
def pow_fn(num_val: CtyValue[Any], power_val: CtyValue[Any]) -> CtyValue[Any]: ...
def signum_fn(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def parseint_fn(str_val: CtyValue[Any], base_val: CtyValue[Any]) -> CtyValue[Any]: ...
