from pyvider.cty import CtyList as CtyList, CtyNumber as CtyNumber, CtyString as CtyString, CtyValue as CtyValue
from pyvider.cty.exceptions import CtyFunctionError as CtyFunctionError
from typing import Any

def chomp(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def strrev(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def trimspace(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def indent(prefix_val: CtyValue[Any], input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def substr(input_val: CtyValue[Any], offset_val: CtyValue[Any], length_val: CtyValue[Any]) -> CtyValue[Any]: ...
def trim(input_val: CtyValue[Any], cutset_val: CtyValue[Any]) -> CtyValue[Any]: ...
def title(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def trimprefix(input_val: CtyValue[Any], prefix_val: CtyValue[Any]) -> CtyValue[Any]: ...
def trimsuffix(input_val: CtyValue[Any], suffix_val: CtyValue[Any]) -> CtyValue[Any]: ...
def regex(input_val: CtyValue[Any], pattern_val: CtyValue[Any]) -> CtyValue[Any]: ...
def regexall(input_val: CtyValue[Any], pattern_val: CtyValue[Any]) -> CtyValue[Any]: ...
def upper(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
def lower(input_val: CtyValue[Any]) -> CtyValue[Any]: ...
