from attrs import define, field
from pyvider.cty.exceptions import CtyAttributeValidationError as CtyAttributeValidationError, CtyTypeMismatchError as CtyTypeMismatchError, CtyValidationError as CtyValidationError, InvalidTypeError as InvalidTypeError
from pyvider.cty.path import CtyPath as CtyPath, GetAttrStep as GetAttrStep
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar

@define(frozen=True, slots=True)
class CtyObject(CtyType[dict[str, object]]):
    ctype: ClassVar[str] = ...
    attribute_types: dict[str, 'CtyType[Any]'] = field(factory=dict)
    optional_attributes: frozenset[str] = field(factory=frozenset)
    def __attrs_post_init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def validate(self, value: object) -> CtyValue[dict[str, Any]]: ...
    def get_attribute(self, obj_value: CtyValue[Any], name: str) -> CtyValue[Any]: ...
    def has_attribute(self, name: str) -> bool: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
    def is_primitive_type(self) -> bool: ...
