from attrs import define, field
from pyvider.cty.exceptions import CtyTupleValidationError as CtyTupleValidationError, CtyTypeMismatchError as CtyTypeMismatchError, CtyValidationError as CtyValidationError
from pyvider.cty.path import CtyPath as CtyPath, IndexStep as IndexStep
from pyvider.cty.types.base import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, ClassVar

@define(frozen=True, slots=True)
class CtyTuple(CtyType[tuple[object, ...]]):
    ctype: ClassVar[str] = ...
    element_types: tuple[CtyType[Any], ...] = field()
    def validate(self, value: object) -> CtyValue[tuple[Any, ...]]: ...
    def element_at(self, container_value: CtyValue[Any], index: int | slice) -> CtyValue[Any]: ...
    def equal(self, other: CtyType[Any]) -> bool: ...
    def usable_as(self, other: CtyType[Any]) -> bool: ...
    def __getitem__(self, index: int | slice) -> CtyType[Any] | CtyTuple | tuple[CtyType[Any], ...]: ...
    def slice(self, container_value: CtyValue[Any], start: int, end: int | None = None, step: int | None = None) -> CtyValue[Any]: ...
