import pytest
from hypothesis import given, strategies as st, settings

from pyvider.cty import CtyObject, CtyString, CtyNumber, CtyList, CtyValidationError

# --- Define a representative schema to test against ---
user_profile_schema = CtyObject(attribute_types={
    "username": CtyString(),
    "email": CtyString(),
    "age": CtyNumber(),
    "tags": CtyList(element_type=CtyString()),
}, optional_attributes=frozenset(["age", "tags"]))

# --- Define Hypothesis strategies for generating data ---

# A strategy that ALWAYS generates data that is VALID for the schema.
valid_user_profile_strategy = st.fixed_dictionaries({
    "username": st.text(min_size=1, max_size=50),
    "email": st.emails(),
    "age": st.one_of(st.none(), st.integers(min_value=0, max_value=120)),
    "tags": st.one_of(st.none(), st.lists(st.text(max_size=20), max_size=10)),
}).map(lambda d: {k: v for k, v in d.items() if v is not None})

# A strategy that generates data that is INVALID for the schema.
# This is now more precise to guarantee validation failure.
invalid_user_profile_strategy = st.one_of(
    # Missing required 'username'
    st.fixed_dictionaries({"email": st.emails()}),
    # 'age' has the wrong type (a non-numeric string)
    st.fixed_dictionaries({
        "username": st.text(min_size=1),
        "email": st.emails(),
        "age": st.text(alphabet=st.characters(whitelist_categories=('L',)), min_size=1)
    }),
    # 'tags' is not a list
    st.fixed_dictionaries({"username": st.text(min_size=1), "email": st.emails(), "tags": st.booleans()}),
    # An element within 'tags' has the wrong type
    st.fixed_dictionaries({"username": st.text(min_size=1), "email": st.emails(), "tags": st.lists(st.integers(), min_size=1)}),
    # An unknown attribute is present
    st.fixed_dictionaries({"username": st.text(min_size=1), "email": st.emails(), "extra_field": st.text()}),
)

@settings(deadline=500, max_examples=200)
@given(data=valid_user_profile_strategy)
def test_schema_accepts_valid_data(data):
    """
    Verifies that any data generated by the valid strategy
    passes schema validation without raising an error.
    """
    try:
        user_profile_schema.validate(data)
    except CtyValidationError as e:
        pytest.fail(f"Schema incorrectly rejected valid data: {data}\nError: {e}")

@settings(deadline=500, max_examples=200)
@given(data=invalid_user_profile_strategy)
def test_schema_rejects_invalid_data(data):
    """
    Verifies that any data generated by the invalid strategy
    is correctly rejected by raising a CtyValidationError.
    """
    with pytest.raises(CtyValidationError):
        user_profile_schema.validate(data)
