import contextlib
from enum import Enum
from pyvider.telemetry import logger as logger

class OperationContext(Enum):
    DEFAULT = ...
    CONFIG = ...
    STATE = ...
    PLAN = ...
    APPLY = ...
    READ = ...
    FUNCTION = ...
    SCHEMA = ...

def get_current_operation() -> OperationContext: ...
def operation_context(context: OperationContext) -> contextlib.AbstractContextManager[None]: ...
