name: 🚀 Continuous Deployment

on:
  workflow_run:
    workflows: ["🧪 CI - Tests & Quality"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  deploy-testpypi:
    name: 🧪 Deploy to TestPyPI
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'

    steps:
      - name: 📥 Download CI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: 📋 Deployment Summary
        run: |
          echo "🎉 Continuous deployment completed!"
          echo "🧪 Deployed to TestPyPI: https://test.pypi.org/project/pyvider-cty/"
          echo "✅ Ready for manual release to production PyPI"

          # List what was deployed
          echo ""
          echo "📦 Deployed packages:"
          ls -la dist/ || echo "No artifacts found"