name: 🚀 Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  continuous-deployment:
    name: 🧪 Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔖 Generate Version for TestPyPI
        id: post-version
        run: |
          # Read base version from file
          BASE_VERSION=$(cat VERSION)
          PACKAGE_NAME="pyvider-cty"

          echo "📦 Base version: $BASE_VERSION"

          # Check if version exists on TestPyPI
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://test.pypi.org/pypi/${PACKAGE_NAME}/${BASE_VERSION}/json" || echo "000")

          if [ "$HTTP_CODE" = "404" ]; then
            # Version doesn't exist, use base version
            DEPLOY_VERSION="$BASE_VERSION"
            echo "✅ Version $BASE_VERSION not found on TestPyPI - using base version"
          else
            # Version exists, create post-release
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            DEPLOY_VERSION="${BASE_VERSION}.post${TIMESTAMP}"
            echo "🔄 Version $BASE_VERSION exists on TestPyPI - using post-release: $DEPLOY_VERSION"
          fi

          echo "🚀 Deploy version: $DEPLOY_VERSION"

          # Update version file
          echo "${DEPLOY_VERSION}" > VERSION

          # Set outputs
          echo "base-version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          echo "post-version=${DEPLOY_VERSION}" >> $GITHUB_OUTPUT
          echo "timestamp=${TIMESTAMP:-none}" >> $GITHUB_OUTPUT

      - name: 🔐 Parse Organization Helpers
        uses: provide-io/ci-tooling/actions/parse-org-helpers@main
        env:
          GH_ORG_HELPERS: ${{ secrets.GH_ORG_HELPERS }}

      - name: 🔐 Setup GitHub Auth
        env:
          GH_ORG_HELPERS: ${{ secrets.GH_ORG_HELPERS }}
        run: python3 scripts/setup_github_auth.py

      - name: 🐍 Setup Python Environment
        uses: provide-io/ci-tooling/actions/setup-python-env@v0.2.3
        with:
          python-version: '3.11'
          install-extras: 'dev'

      - name: 🧪 Run Quick Tests
        uses: provide-io/ci-tooling/actions/python-test@v0.2.3
        with:
          test-directory: 'tests/'
          source-directory: 'src/'
          coverage-threshold: 75

      - name: 📦 Build Package with UV
        run: |
          source ./workenv/bin/activate
          uv build

      - name: 📤 Deploy to TestPyPI with UV
        run: |
          source ./workenv/bin/activate
          uv publish \
            --publish-url https://test.pypi.org/legacy/ \
            --token "${{ secrets.TESTPYPI_API_TOKEN }}" \
            dist/*

      - name: 📋 Deployment Summary
        run: |
          echo "🎉 Continuous deployment completed!"
          echo "📦 Post version: ${{ steps.post-version.outputs.post-version }}"
          echo "📦 Base version: ${{ steps.post-version.outputs.base-version }}"
          echo "🧪 Deployed to TestPyPI: https://test.pypi.org/project/pyvider-cty/"
          echo "✅ Ready for manual release to production PyPI"