name: 🧪 CI - Migrated to Shared Tooling

on:
  push:
    branches: [main, develop, test-ci-tooling]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  # Test using our shared reusable workflow
  ci-reusable:
    name: 🔄 CI (Reusable Workflow)
    uses: provide-io/ci-tooling/.github/workflows/python-ci.yml@v0.0.0
    with:
      python-version: '3.11'
      source-paths: 'src/ tests/'
      test-directory: 'tests/'
      coverage-threshold: 75
      run-security: true
      matrix-testing: true
      os-matrix: 'ubuntu-latest,macos-latest'
      python-matrix: '3.11,3.12,3.13'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Test using individual shared actions for full control
  ci-individual:
    name: 🔧 CI (Individual Actions)
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python Environment
        uses: provide-io/ci-tooling/actions/setup-python-env@v0.0.0
        with:
          python-version: '3.11'
          uv-version: '0.7.8'
          install-extras: 'dev'

      - name: 🎨 Code Quality
        uses: provide-io/ci-tooling/actions/python-quality@v0.0.0
        with:
          source-paths: 'src/ tests/'

      - name: 🧪 Run Tests
        uses: provide-io/ci-tooling/actions/python-test@v0.0.0
        with:
          test-directory: 'tests/'
          source-directory: 'src/'
          coverage-threshold: 75
          pytest-args: '-n auto -v'

      - name: 🔒 Security Scan
        uses: provide-io/ci-tooling/actions/python-security@v0.0.0
        with:
          source-paths: 'src/'

      - name: 🏗️ Build Package
        uses: provide-io/ci-tooling/actions/python-build@v0.0.0
        with:
          build-backend: 'uv'

  # Matrix test demonstrating shared actions work across Python versions
  matrix-test:
    name: 🧪 Matrix (${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python Environment
        uses: provide-io/ci-tooling/actions/setup-python-env@v0.0.0
        with:
          python-version: ${{ matrix.python-version }}
          install-extras: 'dev'

      - name: 🧪 Quick Test
        uses: provide-io/ci-tooling/actions/python-test@v0.0.0
        with:
          test-directory: 'tests/'
          source-directory: 'src/'
          pytest-args: '-xvs --tb=short'
          coverage-threshold: 70

  # Integration test using shared actions
  integration:
    name: 🔗 Integration (Shared Actions)
    runs-on: ubuntu-latest
    needs: [ci-reusable, ci-individual, matrix-test]
    if: github.event_name == 'push' && contains(github.ref, 'test-ci-tooling')
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python Environment
        uses: provide-io/ci-tooling/actions/setup-python-env@v0.0.0
        with:
          python-version: '3.11'
          install-extras: 'dev'

      - name: 🧪 Integration Tests
        uses: provide-io/ci-tooling/actions/python-test@v0.0.0
        with:
          test-directory: 'tests/'
          source-directory: 'src/'
          pytest-args: '-m integration -v || true'
          coverage-enabled: false

  # Summary of shared tooling validation
  summary:
    name: 📊 Migration Summary
    needs: [ci-reusable, ci-individual, matrix-test, integration]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Generate Migration Summary
        shell: bash
        run: |
          echo "## 🔄 CI Tooling Migration Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Type | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Reusable Workflow | ${{ needs.ci-reusable.result == 'success' && '✅ Pass' || '❌ Fail' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Individual Actions | ${{ needs.ci-individual.result == 'success' && '✅ Pass' || '❌ Fail' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Matrix Testing | ${{ needs.matrix-test.result == 'success' && '✅ Pass' || '❌ Fail' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Integration Tests | ${{ needs.integration.result == 'success' && '✅ Pass' || needs.integration.result == 'skipped' && '⏭️ Skip' || '❌ Fail' }} |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.ci-reusable.result }}" = "success" ] && \
             [ "${{ needs.ci-individual.result }}" = "success" ] && \
             [ "${{ needs.matrix-test.result }}" = "success" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🎉 **Migration to shared CI tooling successful!**" >> $GITHUB_STEP_SUMMARY
            echo "Ready to replace existing workflows with shared actions." >> $GITHUB_STEP_SUMMARY
            exit 0
          else
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "⚠️ **Migration incomplete - review failures before proceeding**" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi