name: 🚀 Performance Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    name: 📊 Run Benchmarks
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 📦 Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: 📦 Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
      
      - name: 🏃 Run benchmarks
        run: |
          source .venv/bin/activate
          pytest tests/ \
            --benchmark-only \
            --benchmark-json=benchmark.json \
            --benchmark-autosave || true
      
      - name: 📊 Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: github.event_name != 'pull_request'
        with:
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '150%'
          fail-on-alert: false
      
      - name: 💾 Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            .benchmarks/
            benchmark.json