name: Simple Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello World
        run: |
          echo "Hello from act!"
          echo "Current directory: $(pwd)"
          echo "Files:"
          ls -la
      
      - name: Python Version
        run: |
          python3 --version
          pip3 --version