import abc
from abc import ABC, abstractmethod
from attrs import define, field
from pyvider.cty.exceptions import AttributePathError as AttributePathError, CtyValidationError as CtyValidationError
from pyvider.cty.types import CtyType as CtyType
from pyvider.cty.values import CtyValue as CtyValue
from typing import Any, TypeVar

T = TypeVar('T')

class PathStep(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def apply(self, value: CtyValue[Any]) -> CtyValue[Any]: ...
    @abstractmethod
    def apply_type(self, vtype: CtyType[Any]) -> CtyType[Any]: ...

@define(frozen=True)
class GetAttrStep(PathStep):
    name: str = field()
    def apply(self, value: CtyValue[Any]) -> CtyValue[Any]: ...
    def apply_type(self, vtype: CtyType[Any]) -> CtyType[Any]: ...

@define(frozen=True)
class IndexStep(PathStep):
    index: int = field()
    def apply(self, value: CtyValue[Any]) -> CtyValue[Any]: ...
    def apply_type(self, vtype: CtyType[Any]) -> CtyType[Any]: ...

@define(frozen=True)
class KeyStep(PathStep):
    key: object = field()
    def apply(self, value: CtyValue[Any]) -> CtyValue[Any]: ...
    def apply_type(self, vtype: CtyType[Any]) -> CtyType[Any]: ...

@define
class CtyPath:
    steps: list[PathStep] = field(factory=list)
    @classmethod
    def empty(cls) -> CtyPath: ...
    @classmethod
    def get_attr(cls, name: str) -> CtyPath: ...
    @classmethod
    def index(cls, index: int) -> CtyPath: ...
    @classmethod
    def key(cls, key: object) -> CtyPath: ...
    def child(self, name: str) -> CtyPath: ...
    def index_step(self, index: int) -> CtyPath: ...
    def key_step(self, key: object) -> CtyPath: ...
    def apply_path(self, value: object) -> CtyValue[Any]: ...
    def apply_path_type(self, vtype: CtyType[Any]) -> CtyType[Any]: ...
    def string(self) -> str: ...
